### ISSUE TITLE
Thumbnail images are collosal because client side appears to use original size

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/tgwf2015#1]
On the front page, of the TGWF website, we have a set of thumbnails.

<img width="1215" alt="Screenshot 2020-01-08 at 15 54 15" src="https://user-images.githubusercontent.com/17906/71987962-65250c80-322f-11ea-8007-d939b1c1a202.png">

These look nice, but there's a problem when you look at what we send over the wire, you'll see they are MASSIVE:

<img width="1201" alt="Screenshot 2020-01-08 at 15 55 15" src="https://user-images.githubusercontent.com/17906/71987972-69512a00-322f-11ea-9724-20846c8633c0.png">

You can see our own [full sitespeed report of stuff we need to fix on the site](https://www.thegreenwebfoundation.org/wp-content/uploads/2019-11-07-18-45-45/toplist.html#image
) too, for further details.

### What we need to do

We need to serve appropriate size images on the server side, as we already have stuff like srcset images, which serve different size images to different size browsers/user agents. 

Srcset is fine, but with the original images so huge, when you visit on a full size browser you still see this sad state of affairs.

### Where to look:

Here's the code generating the thumbnail.

https://github.com/thegreenwebfoundation/tgwf2015/blob/master/home.php#L17-L19

We need it to generate smaller thumbnail pics.

Wordpress might have built in tags to generate smaller images for us, or we might need to resort to a plugin, or some custom code to serve sensibly sized images.

I don't know wordpress well enough to know for sure, so I've created this issue to see if a helpful soul might know.

Help, o internet!

**Comment by hanopcan** [comment]
WordPress can definitely do this for you by using code already within it - there's lot of stuff built in you can leverage without the need for a plugin. 

The quickest and easiest way is to pass a thumbnail size into the function that generates the post thumbnail eg

`the_post_thumbnail('large)';`

This will output the large thumbnail size which is usually 640 by 640. 

The default ones are:

Thumbnail (default 150px x 150px max)
Medium resolution (default 300px x 300px max)
Large resolution (default 640px x 640px max)
Full resolution (original size uploaded)

It's very easy to define your own thumbnail sizes if you want. Just use the 'add_image_size' function to functions.php. More info on usage here: https://developer.wordpress.org/reference/functions/add_image_size/

Is that what you needed? Shout if there's anything else you need help with 😄

**Comment by mrchrisadams** [comment]
Hi @hanopcan this was exactly what I needed - danke!

From 9.1 mb (EEK!)
https://www.thegreenwebfoundation.org/wp-content/uploads/2019-11-07-18-45-45/pages/www.thegreenwebfoundation.org/index.html

To 808k (ah, much better…)
https://www.thegreenwebfoundation.org/wp-content/uploads/2020-01-08-16-11-25/pages/www.thegreenwebfoundation.org/index.html

I'm closing this issue now, as until we find someone for the new redesign (f you know anyone…), I think a ~90% drop in transfer over the wire will do.

**Comment by mrchrisadams** [comment]
BTW, for this curious, here was the fix:

https://github.com/thegreenwebfoundation/tgwf2015/commit/1a00198201c7d06320cea41b5912a5ecd57f76e7

Adding 'medium' as an thumbnail size param…
