### ISSUE TITLE
Charts broken on front page

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/tgwf2015#4]
The charts on the front page are no longer displaying, since we included cloudflare.

They currently look like so:
![Screenshot 2020-05-29 at 11 41 44](https://user-images.githubusercontent.com/17906/83245748-743a3600-a1a1-11ea-9861-58fc25ef6dee.png)

It might be unrelated to but we see this error , when we try to fetch the data from our graphite install.

```
Chris Adams:
Traceback (most recent call last):
File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/graphite/webapp/graphite/render/views.py", line 144, in renderView
response = renderViewGraph(graphOptions, requestOptions, data)
File "/opt/graphite/webapp/graphite/render/views.py", line 164, in renderViewGraph
image = doImageRender(requestOptions['graphClass'], graphOptions)
File "/opt/graphite/webapp/graphite/render/views.py", line 569, in doImageRender
img = graphClass(**graphOptions)
File "/opt/graphite/webapp/graphite/render/glyph.py", line 575, in __init__
self.drawGraph(**params)
File "/opt/graphite/webapp/graphite/render/glyph.py", line 1091, in drawGraph
self.setupYAxis()
File "/opt/graphite/webapp/graphite/render/glyph.py", line 1468, in setupYAxis
yTics.chooseLimits()
File "/opt/graphite/webapp/graphite/render/glyph.py", line 497, in chooseLimits
raise GraphError('Logarithmic scale specified with a dataset with a '
GraphError: Logarithmic scale specified with a dataset with a minimum value less than or equal to zero
```

So the django app backing it is erroring out when trying to draw the chart

```
GraphError: Logarithmic scale specified with a dataset with a minimum value less than or equal to zero
```

**Comment by arendjantetteroo** [comment]
I think it's related to me updating the api code, i think both of these charts are based on data points inserted from the api. Cloudflare can minimize the numbers but not remove all of them. 

I needed to update the statsd vendor code we use, possibly this is no longer sending it to the right server endpoint/url?

**Comment by arendjantetteroo** [comment]
https://github.com/thegreenwebfoundation/greencheck-api/blob/master/config/packages/liuggio_stats_d_client.yaml

**Comment by arendjantetteroo** [comment]
that is the config we use, possibly the env part is not correctly setup anymore in the workers? Or the bundle we use is now breaking as it's symfony 5 now?

**Comment by mrchrisadams** [comment]
I've had a look into the graphite dashboard, and it looks like the greencheck count dropped off on 19th, so the statsd thing no longr sending sounds about right:

![zero--checks-graphite thegreenwebfoundation org](https://user-images.githubusercontent.com/17906/83263264-9db58a80-a1be-11ea-8b6f-2c3dc68235d8.png)

The chart query, decoded looks like so:

```
https://graphite.thegreenwebfoundation.org/render/?
width=230
height=175
_salt=1409819122.824
target=alias(hitcount(stats.api.greencheck_job.checks,"1d"),"Checks per hour")
logBase=10
bgcolor=FFFFFF
colorList=#70ba2b
fgcolor=000000
title=Greenchecks performed per day
from=-1months
hideLegend=true
xFormat=%d-%m
yUnitSystem=none
hideGrid=true
```

My guess is that when we take a day's worth of checks and show some stats on a per hour basis, some of the maths is dividing by zero, causing the crash.

@arendjantetteroo this sounds like it might indeed be a vendor thing.

Is this you're happy looking at next week? I'm okay with looking, but I think you might be faster.

**Comment by arendjantetteroo** [comment]
@mrchrisadams i can take a look either tonight or tomorrow. Will let you know what i find. we might want to switch them to the log monitor keys instead

**Comment by mrchrisadams** [comment]
Sorry - I don't think I know what the _log monitor keys_ refers to. Where should I be looking learn more?

**Comment by arendjantetteroo** [comment]
under /root/logmonitor a script is running crawling to the access logs of nginx and putting those into statsd.

**Comment by arendjantetteroo** [comment]
Take a look into app/config/*.yaml files. either the parser or actor mentioned there contains the statsd keys that we log to.

**Comment by arendjantetteroo** [comment]
https://status.thegreenwebfoundation.org/ is also showing empty stuff

**Comment by arendjantetteroo** [comment]
btw, i'm not sure we already pushed that into a github repo, but we should if not

**Comment by arendjantetteroo** [comment]
I've got a hunch it was the cloudflare thing after all. We are using api.thegreenwebfoundation.org to connect to the statsd server. But this domain now points to cloudflare's cdn servers.

**Comment by arendjantetteroo** [comment]
@mrchrisadams it's coming back. It was indeed the cloudflare switch.

**Comment by arendjantetteroo** [comment]
https://graphite.thegreenwebfoundation.org/render/?width=586&height=308&target=stats.api.greencheck_job.checks&from=00%3A00_20200501&until=23%3A59_20200529&_salt=1590766706.501

**Comment by arendjantetteroo** [comment]
![download](https://user-images.githubusercontent.com/713066/83278083-4f5eb680-a1d3-11ea-8882-1ce8a17e14d5.png)

**Comment by mrchrisadams** [comment]
Woot!

So the UDP packets were being sent to what amounted to a cloudflare server, rather than our one, right?

**Comment by mrchrisadams** [comment]
If that's the case, I think we can close this issue. Feel free to close if this is the case.

**Comment by arendjantetteroo** [comment]
Well, chart is still not showing due to the data missing. So i'm looking at fixing that

**Comment by arendjantetteroo** [comment]
Ok, i replaced the chart without the logScale. Looks a bit less nice, but at least it shows something. I'll close this issue.
